### ISSUE TITLE
Error when syncing products with emoji

### ISSUE THREAD

**Issue by tommysvr** [craftcms/shopify#107]
### Description
When trying to sync products with emoji in the title or description, getting an error: `General error: 1366 Incorrect string value: '\xF0\x9F\x8D\x83' for column 'bodyHtml' at row 1 in /var/www/html/vendor/yiisoft/yii2/db/Command.php:1302`

### Steps to reproduce

1. Create a Shopify product with an emoji in the title or description
2. Run `php craft shopify/sync/products`

### Additional info

- Craft version: 4.8.9
- PHP version: 8.2
- Database driver & version: MySQL 8.0
- Plugins & versions: Shopify 4.1.1

**Comment by nfourtythree** [comment]
This is now fixed in versions `4.1.2` and `5.1.1` of the plugin.

Thanks!
