### ISSUE TITLE
Request: Increase max character limit on input field

### ISSUE THREAD

**Issue by idawgik** [craftcms/shopify#25]
We have a client using this fieldtype to add Shopify products to their blog posts. However, they are running into an error selecting products where it says "[FIELDNAME] should contain at most 255 characters.".

There aren't any settings in the plugin to adjust that. Some of their products have a lot of variants, so the name with the skus appended gets pretty long. This is causing them not able to add the products they want.

Is there a way to increase this limit? Or add an option to control what this limit is such as with a standard text input fieldtype?

**Comment by nmaier95** [comment]
Seems to me like some limitation by your database field settings. You might have to increase that If possible. Else you might need to think of some different sort of saving your "bigger" load of data (or fetch it async on page load or something...?).

**Comment by idawgik** [comment]
Well, in Craft CMS for the default plain text fields, there's an option to change what database field type is used under the advanced section of the field settings. That doesn't exist for this plugin, so outside of modifying it directly in MySql, there isn't a way to change it.

Ideally the plugin could be updated to provide the same option to update the database field type from the admin, same as the Plain Text fieldtype in native Craft CMS.

**Comment by nmaier95** [comment]
Oh ok, didn't know. Feel free to create a PR to modify field settings.

**Comment by AugustMiller** [comment]
Hi, all!

Now that the plugin is under Pixel & Tonic’s wing, we've released version 3.0 which includes a number of fixes.

The updated field type uses Craft’s native relations system, so there are no more limitations on the number of products you can attach.
