### ISSUE TITLE
Request: Return product name and slug alongside id?

### ISSUE THREAD

**Issue by riccardolardi** [craftcms/shopify#27]
Would it be possible to return product name and slug alongside the id?

**Comment by AugustMiller** [comment]
Hi!

Now that the plugin is under Pixel & Tonic’s wing, we've released version 3.0 which includes a number of fixes.

Craft now synchronizes products into elements, so you get back a fully-featured Product object in the template.

```twig
{{ product.title }}
{{ product.slug }} (or {{ product.handle }}, if you want Shopify’s version!)
```
