### ISSUE TITLE
No GraphQL support

### ISSUE THREAD

**Issue by mediabeastnz** [craftcms/shopify#48]
### Description
After installing this plugin and navigating to Graphiql it seems there is no way to query for product data?

### Steps to reproduce

1. Install plugin
2. Use graphiql to test for GQL support

### Additional info

- Craft version: 4.3.4
- PHP version: 8.0
- Database driver & version: mysql 5.7
- Plugins & versions: 3.0.1

**Comment by brandonkelly** [comment]
Not really a bug as much as something we didn’t get around to yet. You can follow along at #49 for updates!
