### ISSUE TITLE
Issue with Craft headlessMode config

### ISSUE THREAD

**Issue by QuentinLeclercq** [craftcms/shopify#68]
### Description
Using Craft with [headlessMode](https://craftcms.com/docs/4.x/config/general.html#headlessmode) creates error when saving Shopify plugin settings.

### Error

```
PHP Warning – [yii\base\ErrorException](https://www.yiiframework.com/doc-2.0/yii-base-errorexception.html)
Undefined array key "template"
```

<img width="2178" alt="Capture d’écran 2023-05-25 à 10 45 11" src="https://github.com/craftcms/shopify/assets/5969960/ebcf8c25-4732-4f20-8c40-ee9c10ca500c">

### Steps to reproduce

1. In config/general.php, set `headless` mode to `true`
2. Go to Shopify plugin settings, hit the Save button
3. Error appears

### Additional info

- Craft version: 4.4.12
- PHP version: 8.0.5
- Database driver & version : MariaDB 10.11.3
- Shopify plugin version: 3.1.1

**Comment by lukeholder** [comment]
Looking at that error, it's coming from the old version of the plugin in your composer.json installed into your vendor directory called "shopify-product-fetcher".

Make sure you have the correct package in your composer.json

`composer require craftcms/shopify -w`

and remove the old one and do a

`composer update`

**Comment by QuentinLeclercq** [comment]
Hey @lukeholder, thanks for your quick answer!

Still experiencing the same issue after removing `nmaier95/shopify-product-fetcher` and adding/installing `craftcms/shopify`.

I'm not sure to understand how it can works here: https://github.com/craftcms/shopify/blob/develop/src/controllers/SettingsController.php#L67

The `template` key isn't send when we enable `headless` mode, which is normal I guess. See the `routing` content in the POST request. We only have `uriFormat`.

<img width="416" alt="image" src="https://github.com/craftcms/shopify/assets/5969960/4f643b47-27e9-4774-af2a-6979fa7b9dc0"><br>

So the `Undefined array key "template"` error looks like to be relevant. If I add a check on the template key like in the image below, saving worked:<br>
<img width="456" alt="image" src="https://github.com/craftcms/shopify/assets/5969960/f2a9137e-a226-4164-a47c-68f9fb5e8f36">

Thanks for you help!

**Comment by andrevvm** [comment]
Hi @lukeholder, I'm having the same issue as Quentin here. Even after changing the config to `headlessMode(false)` and reinstalling Shopify app.

Temporarily bypassing with Quentin's solution above...

**Comment by curtishenson** [comment]
Yeah this is a legitimate bug, looks like there is already a pull request to fix this as well #57

**Comment by lukeholder** [comment]
Thanks everyone. I'll get a fix out shortly.

**Comment by lukeholder** [comment]
This is now out in 3.2.0!

See the notes in the [upgrading section](https://github.com/craftcms/shopify#upgrading) of the README
