### ISSUE TITLE
Product metafields not syncing

### ISSUE THREAD

**Issue by shadowfox** [craftcms/shopify#69]
### Description

Project metafields don't appear to be syncing, with the value always being an empty array in the database.

### Steps to reproduce

1. Update product metafields in Shopify
2. Utilities > Shopify Sync > Sync all products
3. Observe meta fields are empty

### Additional info

- Craft version: 4.4.1.3
- PHP version: 8.1
- Database driver & version:
- Plugins & versions: craftcms-shopify 3.1.1

**Comment by lukeholder** [comment]
Thanks for reporting, I will look into this soon.

**Comment by curtishenson** [comment]
Ran into this so I tried to do some digging. Hopefully it will help you troubleshoot it:

- The API returns the meta fields and everything else seems right, but it never saves metaFields to the database.
- I can get the meta fields to save to the DB if I switch the [job](https://github.com/craftcms/shopify/blob/df126ea3705ed3717fddf1ef7dade9146056a990/src/jobs/UpdateProductMetadata.php#L20) to use:
```
if ($this->shopifyProductId) {
   Plugin::getInstance()->getProducts()->syncProductByShopifyId($this->shopifyProductId);
   sleep(1); // Avoid rate limiting
}
```

After that I needed to add `public array $metaFields = [];` to the [Product element](https://github.com/craftcms/shopify/blob/df126ea3705ed3717fddf1ef7dade9146056a990/src/elements/Product.php#L87) to actually access them.

**Comment by shadowfox** [comment]
@lukeholder Hey just a friendly follow-up to see if we've had any movement on this one.

**Comment by lukeholder** [comment]
Thanks for following up.

This has been fixed for the next release.

To get the fix early, change your `craftcms/shopify` requirement in composer.json to:

```json
"require": {
  "craftcms/shopify": "dev-develop#411c7cbe343d7c5e16e937615c22c522c24989c5 as 3.1.1",
  "...": "..."
}
```

Then run `composer update`.


Thanks

**Comment by lukeholder** [comment]
4.0.0 is now out. Make sure to read the [changelog item](https://github.com/craftcms/shopify/blob/develop/CHANGELOG.md#400---2023-11-02) to learn what you need to do to upgrade. The readme also [contains instructions](https://github.com/craftcms/shopify#upgrading).
