### ISSUE TITLE
Shopify email notification link templates

### ISSUE THREAD

**Issue by davidcraigmyle** [craftcms/shopify#74]
### Description
Hey,

I have built a site with the Shopify plugin and Buy Buttons.
The plan was to keep the shop experience on the Craft site and only use Shopify through the buy button functionality.
This works, mostly, as I have the products pulled through, set the ID for the buy button, and have the cart pop up.

The only issue I have is when the cart opens, the logo at the top links to the Shopify site.
This is also an issue in the email notification templates, where the payment error and payment reminder buttons, for example, have Shopify variables as links, so when a customer clicks them, they get taken to the Shopify site.
Templates like the abandoned cart template can easily have hard-coded links to the Craft site, but when there is a specific page needed, we don't have a template on Craft.

Is there a plan (or an easy solution I am missing) to have these templates handled within Craft?
Then I'd be able to change the links in the notification templates to the Craft site instead of the variable links to the Shopify site.

I have the Shopify site password protected to keep users on the Craft site as well but if they click the links in the email notifications they will be confused.

![Screenshot 2023-07-17 at 09 53 21](https://github.com/craftcms/shopify/assets/19872210/c96b028a-af2b-4c7b-ad7a-1f5cac31d713)

### Additional info

- Craft version: 4.3.6
- PHP version: 8.1.20
- Database driver & version: MySQL 5.7.42
- Plugins & versions: 3.1.0

**Comment by lukeholder** [comment]
Hi @davidcraigmyle 

Interesting issue - that's not ideal.

Im not sure if it would get you closer to what you are wanting, but what happens if you delete the “Online Store” sales channel, and only use your app sales channel? I wonder if Shopify then understands that there is no website with a URL and those links are disabled?

I would contact Shopify support to see if this is what they would advise or ask them what the best way to customize the logo links etc.

Let me know how you go.

**Comment by davidcraigmyle** [comment]
Thanks, @lukeholder , speedy reply!

That looks like it would work fine. 
It still takes the user to Shopify for their cart and for any of the email templates, but if there are no other links on these pages it shouldn't confuse customers too much.

I'll also get in touch with Shopify just to see what they think.

**Comment by lukeholder** [comment]
Will reopen if there is anything we can do on out side.
