### ISSUE TITLE
refHandle does not parse properly because of the dash

### ISSUE THREAD

**Issue by nichxlson** [craftcms/shopify#77]
### Description

Redactor plugin doesn't parse the `refHandle` because of the dash.

### Steps to reproduce

1. Add a link in a redactor field in this format: `https://example.com#shopify-products:[id]@1:url` and save the entry
  * The link doesn't parse and goes to example.com
2. Change the `refHandle` field in elements/Product.php from `shopify-products` to `shopifyproducts`
3. Change the link in redactor to `https://example.com#shopifyproducts:[id]@1:url` and save the entry
4. The link now parses properly and when you make changes where the product URI is updated the redactor field link will also update

### Additional info

- Craft version: 4.4.8
- PHP version: 8.0.28
- Database driver & version: MySQL 8.0.27
- Plugins & versions: Redactor 3.0.4  & Shopify 3.1.1

**Comment by lukeholder** [comment]
This has been fixed for the next release. The ref handle has been changed to `shopifyproduct`. Will update this issue once 4.0 is out. Thanks.

**Comment by lukeholder** [comment]
4.0.0 is now out. Make sure to read the [changelog item](https://github.com/craftcms/shopify/blob/develop/CHANGELOG.md#400---2023-11-02) to learn what you need to do to upgrade. The readme also [contains instructions](https://github.com/craftcms/shopify#upgrading).
