### ISSUE TITLE
Upgrade Shopify API requirement to `5.x`

### ISSUE THREAD

**Issue by nfourtythree** [craftcms/shopify#81]
### Description
This will give access to the latest Shopify API versions but is also a breaking change as they removed `2022-01` support in `5.0.0`

**Comment by lukeholder** [comment]
This is fixed for the next release. I wiIll update this issue once Shopify 4.0 is out.

**Comment by lukeholder** [comment]
4.0.0 is now out. Make sure to read the [changelog item](https://github.com/craftcms/shopify/blob/develop/CHANGELOG.md#400---2023-11-02) to learn what you need to do to upgrade. The readme also [contains instructions](https://github.com/craftcms/shopify#upgrading).
