### ISSUE TITLE
Customise Sources Isn't Applying for Shopify Products

### ISSUE THREAD

**Issue by sm9** [craftcms/shopify#86]
### Description
I just tried to customise the sources for Shopify Products in my local dev environment. The table columns are customised fine locally, and the project config is updated locally as expected. But when I commit and deploy this project config change to the live environment, the updated source views won't apply. Customising sources works and applies fine for entries, so this seems to be a bug with Shopify Products only? Happy to test/try anything if it's just me though! :) Thanks.

### Steps to reproduce
1. Go to Shopify > Products
2. Click 'Customise Sources' button
3. Customise the columns you want to appear for the Products
4. Push the project config update to another environment
5. The customised columns don't apply

### Additional info
- Craft version: 4.5.9
- PHP version: 8.0
- Database driver & version: MySQL 8
- Plugins & versions: Shopify 4.0.0

**Comment by lukeholder** [comment]
Hi @sm9 sorry for the delay on this one. Can you confirm this is still an issue? Will then look into it again fresh.
