### ISSUE TITLE
Plugin Compatible with Craft 3 in 2024?

### ISSUE THREAD

**Issue by kschiffli-reusser** [craftcms/shopify#91]
### Description
Is this plugin still compatible with Craft 3? The settings field asks for a "Password" but from what I can tell, that refers to a password for a Shopify Private App which are now deprecated. Is it possible to use this plugin with Craft 3 and a Custom Shopify App with a Shopify Admin Access Token?

![Shopify-Plugin-Settings-Craft3](https://github.com/craftcms/shopify/assets/123586000/381f9b3c-e3c0-43fe-854f-89fc2e0fd335)

### Steps to reproduce

1.
2.

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by lukeholder** [comment]
We do not support the Shopify plugin before version 3, unfortunately.

We encourage you to upgrade to the latest Craft release.
