### ISSUE TITLE
The Readme migration section is gone

### ISSUE THREAD

**Issue by AmandaLutzTO** [craftcms/shopify#97]
I was just using it 2 days ago. Is it incorrect or was removing it a mistake?

`Note
Upgrading? Check out the [migration](https://github.com/craftcms/shopify#migrating-from-v2x) notes for more info.`

**Comment by nfourtythree** [comment]
Hi @AmandaLutzTO 

Thank you for your message. In preparation for the release of Craft 5 we have tagged a new version of this plugin with all of the compatibility updates.

With this the migration section is no longer applicable as you must already been on version `4.x` of the plugin to upgrade to `5.0`.

We were probably slightly premature to merge this into the `develop` branch so our apologies for that. 

Don't worry though as you can still get to the documentation via the [v4 branch](https://github.com/craftcms/shopify/tree/v4) which still has all the information you are looking for.

Hope this helps, thanks!
